#!/bin/bash
#
#
# kasutajate lisamise skript
if [ $# -ne 2 ]; then
    echo "Kasutusjuhend: $0 kasutajad ja paroolid"
else
kasutajad=$1
paroolid=$2
  if [ -f $kasutajad -a -r $kasutajad ] && [ -f $paroolid -a -r $paroolid ]; then
    echo "failid on korras"
    for rida in $(paste -d: $kasutajad $paroolid)
    do
      # sellega peaks faili sisu olema nähtav, kui fail on kätte saadav ja n▒$ ▒üd echo asemel tuleb kutsuda vajalik skript
      # echo $nimi
kasutajanimi=$(echo "$rida" | cut -f1 -d:)
      sh lisa_kasutaja $kasutajanimi # sellega me laseme lisa_kasutaja skript töö
echo "$rida" | chpasswd
    done
  else
    echo "probleem failiga $failinimi"
  fi
# parameetrite kontrolli lõpp
fi
